# Generated by Django 5.0.7 on 2024-08-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='audio_is_ai_generated',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='detection',
            name='image_is_ai_generated',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='detection',
            name='video_is_ai_generated',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
